version: "3.8"
services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
  server:
    build: server
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs
      - ./server:/usr/src/app
    depends_on:
      - mongodb
  # add python server steps
  pyserver:
    build: server/python utils
    ports:
      - "8001:8001"
    volumes:
      - logs:/app/logs
      - ./pyserver:/usr/src/app
    depends_on:
      - mongodb
  client:
    build: client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - server
      - pyserver

volumes:
  data:
  logs:
