name: CI

on:
  push:
    branches:
      - main
      - testdev
      - vedant

jobs:
  build:
    name: Build and Test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install

      # - name: Run frontend tests
      #   run: |
      #     cd client
      #     npm test -- --watchAll=false

      - name: Run backend tests
        run: |
          cd server
          npm test

      - name: Build frontend
        run: |
          cd client
          npm run build

      # - name: Run linting
      #   run: |
      #     cd client
      #     npm run lint
      #     cd ../server
      #     npm run lint

      # - name: End to end tests
      #   run: |
      #     # Add end-to-end tests here if applicable
