name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          cd frontend
          npm install
          cd ../backend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test -- --watchAll=false

      - name: Run backend tests
        run: |
          cd backend
          npm test

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Run linting
        run: |
          cd frontend
          npm run lint
          cd ../backend
          npm run lint

      - name: End to end tests
        run: |
          # Add end-to-end tests here if applicable
